### ISSUE TITLE
Name Space

### ISSUE THREAD

**Issue by myalo** [ahhsoftware/sql-plus-version-four-builder#4]
I have an issue with building a project and getting the correct Name Space
First I tried entering the Name Space I want - Achieve.Enterprise. After the build I got namespace Achieve.Enterprise.Achieve.Enterprise.Models 
Second test - leave the Name space field empty.  The screen shows an exclamation mark and on hover, it says Name Space is required.  I tried to build it anyways and the name space after the build is namespace Achieve.Enterprise..Models (two dots). The build json looks like that:
{"SQLClient":"Microsoft.Data.SqlClient","SQLClientNamespace":"System.Data.SqlClient","SQLExceptionNamespace":"System.Data","Template":"NET","DBRoutines":null,"DBSchemas":[{"Schema":"dbo","Namespace":""}],"QuerySchemas":null,"QueryRoutines":null,"EnumQueries":null,"StaticQueries":null,"BuildOptions":{"ImplementIChangeTracking":false,"ImplementIRevertibleChangeTracking":false,"ImplementINotifyPropertyChanged":false,"UseNullableReferenceTypes":false}}
Third test: I saw in https://www.sqlplus.net/documentation/code-generation that is uses "Default" as the name space. What I got is a whole new folder "Default" and under it Models and Services folder.
Fourth test: Entering again Achieve.Enterprise in the name space and the Error is "Must be a valid C# identifier"

How can I configure the build to Get Achieve.Enterprise in all generated files and have the  Models and Service folder under the root of the project?
Thanks

**Comment by ahhsoftware** [comment]
Create your project as Achieve.Enterprise and in the UI user + for the
namespace

**Comment by myalo** [comment]
The + in the Name Space fields worked!  (Hidden feature 🙂)

I discovered another issue:
I am recompiling my class library with .net 8 and as System.Data.SqlClient did not work with .Net 8. I use only Microsoft.Data.SqlClinet which I specified in the builder dialog. The using statement in the generated files is OK except in the following files - ServiceBase.cs, TransientErrors.cs whice still referenec System.Data.SqlClient which causes errors.


Error text:
"The type name 'SqlException' could not be found in the namespace 'System.Data.SqlClient'. This type has been forwarded to assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.   Achieve.Enterprise      C:\Dev\Achieve\2022Projects\Achieve.Enterprise\Default\Services\ServiceBase.cs      136"

Thanks
Moshe

________________________________

**Comment by ahhsoftware** [comment]
I'll look into that. Thanks for the heads up.

**Comment by myalo** [comment]
Thanks
Moshe

________________________________

**Comment by ahhsoftware** [comment]
I updated the plugin to fix the SQL client issue. Also added Async methods and changed the license to MIT.
